# Generated by Django 2.2.4 on 2019-10-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20191030_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='user_images/'),
        ),
    ]
