# Generated by Django 3.0.2 on 2020-03-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200221_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.svg', upload_to='user_images/', verbose_name=''),
        ),
    ]
