# Generated by Django 3.0.1 on 2019-12-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_script', models.FileField(upload_to='ScriptBots/')),
                ('file_config', models.FileField(upload_to='ScriptBots/')),
                ('access_token', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
            ],
        ),
    ]
