# Generated by Django 3.0.2 on 2020-01-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file_config',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bot',
            name='file_script',
            field=models.FileField(upload_to=''),
        ),
    ]
