# Generated by Django 2.2.4 on 2019-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0002_auto_20191030_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='file',
            new_name='file_script',
        ),
    ]
