# Generated by Django 3.0.2 on 2020-02-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0002_auto_20200131_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file_config',
            field=models.FileField(max_length=200, upload_to='DBScriptsBots/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='file_script',
            field=models.FileField(max_length=200, upload_to='DBScriptsBots/'),
        ),
    ]
