# Generated by Django 2.2.4 on 2019-10-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0003_auto_20191030_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file_script',
            field=models.FileField(upload_to='ScriptBots/'),
        ),
    ]
