# Generated by Django 3.0.2 on 2020-03-25 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0003_auto_20200217_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
