# Generated by Django 2.2.6 on 2019-11-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0004_auto_20191030_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='file_config',
            field=models.FileField(default=False, upload_to='ScriptBots/'),
            preserve_default=False,
        ),
    ]
