# Generated by Django 2.2.6 on 2019-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0005_bot_file_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file_config',
            field=models.FileField(max_length=2000, upload_to='ScriptBots/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='file_script',
            field=models.FileField(max_length=2000, upload_to='ScriptBots/'),
        ),
    ]
