# Generated by Django 2.2.6 on 2019-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots', '0006_auto_20191118_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file_config',
            field=models.FileField(upload_to='ScriptBots/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='file_script',
            field=models.FileField(upload_to='ScriptBots/'),
        ),
    ]
